import { betterAuth } from 'better-auth';
import { drizzleAdapter } from 'better-auth/adapters/drizzle';

import { db } from '@/db';
import { users } from '@/db/schema/users';
import { accounts } from '@/db/schema/accounts';
import { verifications } from '@/db/schema/verifications';
import { sessions } from '@/db/schema/sessions';

export const auth = betterAuth({
  secret: process.env.BETTER_AUTH_SECRET,
  url: process.env.BETTER_AUTH_URL,
  database: drizzleAdapter(db, {
    provider: 'pg',
    schema: {
      user: users,
      account: accounts,
      verification: verifications,
      session: sessions
    }
  }),
  emailAndPassword: {
    enabled: true,
    requireEmailVerification: false,
    minPasswordLength: 8,
    maxPasswordLength: 100,
    autoSignIn: true
  },
  advanced: {
    database: {
      generateId: false // uuid will be generated by supabase
    }
  }
});
