services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./src/db/seed:/docker-entrypoint-initdb.d

volumes:
  postgres:
